### ISSUE TITLE
Does not work in meteor.js

### ISSUE THREAD

**Issue by pstoll** [videojs/vtt.js#13]
We are running into an issue when using video.js in meteorjs because of this library.

This package is failing to load because `root.VTTRegion` is undefined here:
 https://github.com/videojs/vtt.js/blob/master/lib/vttregion-extended.js#L29

If I add a 

```
module.exports.VTTRegion = this.VTTRegion;
```

at the very end of https://github.com/videojs/vtt.js/blob/master/lib/vttregion.js#L138 it all works nicely.

Would you be open to adding that modules.exports definition if I make a PR?

**Comment by misteroneill** [comment]
@pstoll It'd absolutely be welcome. We always appreciate any help making our libraries more compatible with other libraries/frameworks!

cc @gkatsev

**Comment by gkatsev** [comment]
This is probably fine, though, I would be a bit weary because the more we modify the main files, the harder it'll be updating from upstream.

**Comment by gkatsev** [comment]
Looks like I just ran into this when trying out rollup in video.js.

**Comment by gkatsev** [comment]
I'm working on this.
